--- #YAML:1.0
name:               URI-cpan
version:            1.004
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CPAN::DistnameInfo:  0
    URI:                 0
resources:
    repository:  http://github.com/rjbs/uri-cpan
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
